# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  # def setup_method(self, method):
  #   self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
  #   self.vars = {}
  #
  # def teardown_method(self, method):
  #   self.driver.quit()
  
  def test_test(self,browser):
    # Test name: test
    # Step # | name | target | value
    # 1 | open | /console/home |
    self.driver = browser[0]
    self.driver.get("http://yundun.test.nodevops.cn/console/home")
    # 2 | setWindowSize | 1936x1056 | 
    self.driver.set_window_size(1936, 1056)
    # 3 | click | css=.FeMenuItemGroup:nth-child(2) > .FeMenuItemGroup__header | 
    self.driver.find_element(By.CSS_SELECTOR, ".FeMenuItemGroup:nth-child(2) > .FeMenuItemGroup__header").click()
    # 4 | click | css=.FeMenuItemGroup--open .FeMenuChildren:nth-child(1) .FeMenuChildren__title | 
    self.driver.find_element(By.CSS_SELECTOR, ".FeMenuItemGroup--open .FeMenuChildren:nth-child(1) .FeMenuChildren__title").click()
    # 5 | click | css=.el-input-group > .el-input__inner | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-input-group > .el-input__inner").click()
    # 6 | type | css=.el-input-group > .el-input__inner | a11
    self.driver.find_element(By.CSS_SELECTOR, ".el-input-group > .el-input__inner").send_keys("a11")
    # 7 | click | css=.el-icon-search | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-icon-search").click()
    # 8 | click | linkText=a11.ssl.ic110.cn | 
    self.driver.find_element(By.LINK_TEXT, "a11.ssl.ic110.cn").click()

  
