# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestnewweb():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testnewweb(self):
    self.driver.get("http://yundun.test.nodevops.cn/console/cloud-speed/businessList/websiteList")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.CSS_SELECTOR, ".FeMenuItemGroup:nth-child(3) > .FeMenuItemGroup__header").click()
    self.driver.find_element(By.CSS_SELECTOR, ".FeMenuItemGroup--open .FeMenuChildren:nth-child(3) .FeMenuChildren__title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--primary:nth-child(1) > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-button--primary:nth-child(1) > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-textarea__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-textarea__inner").send_keys("13.13.13.13")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item__content > .el-select .el-input__inner").click()
    self.driver.find_element(By.XPATH, "//li[contains(.,\'测试集群\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--primary:nth-child(2) > span").click()
  
